version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_waterapp
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: waterapp_db
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    volumes:
      - ./mysql/data:/var/lib/mysql
    networks:
      - forum-network

networks:
  forum-network:
    driver: bridge
